export enum BuildingType {
  Rumah = "rumah",
  Apartemen = "apartemen",
  Ruko = "ruko",
  Tanah = "tanah",
  Gudang = "gudang",
  Gedung = "gedung",
  Hotel = "hotel",
  Pabrik = "pabrik",
  RuangUsaha = "ruang usaha",
  RumahKantor = "rumah kantor",
  SpaceKantor = "space kantor",
  SpaceMall = "space mall",
  Toko = "toko",
  Villa = "villa",
}
